# Generated by Django 5.1.3 on 2024-12-05 17:35

import datetime
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import usos_backend.usos_api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher')], editable=False, max_length=10)),
                ('first_name', models.CharField(default='name_example', max_length=255)),
                ('last_name', models.CharField(default='Lname_example', max_length=255)),
                ('email', models.EmailField(default='example@example.com', max_length=254, unique=True)),
                ('birth_date', models.DateField(default=datetime.date(2010, 1, 1))),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=15)),
                ('status', models.CharField(choices=[('A', 'Active'), ('U', 'Inactive')], default='A', max_length=31)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['id'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryAttendanceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryGradeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryStudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(blank=True, max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='ConsentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('is_mandatory', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='usos_api.parent')),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipients', models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=2700), validators=[usos_backend.usos_api.models.validate_duration])),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.schoolsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='GradeColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('weight', models.IntegerField(default=1)),
                ('description', models.TextField(blank=True, default='')),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.schoolsubject')),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('level', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usos_api.categorystudentgroup')),
                ('students', models.ManyToManyField(related_name='student_groups', to='usos_api.student')),
            ],
        ),
        migrations.AddField(
            model_name='schoolsubject',
            name='student_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.studentgroup'),
        ),
        migrations.CreateModel(
            name='ParentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_consent', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('consent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.consenttemplate')),
                ('parent_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.parent')),
                ('child_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('count_to_avg', models.BooleanField(default=True)),
                ('value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usos_api.categorygradevalue')),
                ('grade_column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.gradecolumn')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.student')),
            ],
        ),
        migrations.AddField(
            model_name='consenttemplate',
            name='students',
            field=models.ManyToManyField(related_name='consent_templates', to='usos_api.student'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_reason', models.TextField(null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usos_api.categoryattendancestatus')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.meeting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.student')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('start_time', models.DateTimeField()),
                ('duration', models.DurationField(default=datetime.timedelta(seconds=2700), validators=[usos_backend.usos_api.models.validate_duration])),
                ('school_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.schoolsubject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_meetings', to='usos_api.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='consenttemplate',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usos_api.teacher'),
        ),
    ]
