# Generated by Django 5.1.3 on 2024-12-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='topic',
            new_name='title',
        ),
    ]
