# Generated by Django 5.1.3 on 2024-12-03 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usos_api.student'),
            preserve_default=False,
        ),
    ]
