# Generated by Django 5.1.3 on 2024-12-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0004_remove_attendance_updated_at_remove_meeting_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmeeting',
            name='start_time',
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='day_of_week',
            field=models.IntegerField(choices=[(1, 'Poniedziałek'), (2, 'Wtorek'), (3, 'Środa'), (4, 'Czwartek'), (5, 'Piątek')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scheduledmeeting',
            name='slot',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
