# Generated by Django 5.1.3 on 2024-12-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0005_remove_scheduledmeeting_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='slot',
            field=models.IntegerField(choices=[(1, '08:00 - 08:45'), (2, '08:55 - 09:40'), (3, '09:50 - 10:35'), (4, '10:45 - 11:30'), (5, '11:40 - 12:25'), (6, '12:45 - 13:30'), (7, '13:40 - 14:25'), (8, '14:35 - 15:20')]),
        ),
    ]
