# Generated by Django 5.1.3 on 2024-12-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0006_alter_scheduledmeeting_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledmeeting',
            name='place',
            field=models.IntegerField(choices=[(10, 'Sala 10'), (11, 'Sala 11'), (12, 'Sala 12'), (13, 'Sala 13'), (14, 'Sala 14'), (15, 'Sala 15'), (16, 'Sala 16'), (17, 'Sala 17'), (18, 'Sala 18'), (19, 'Sala 19'), (20, 'Sala 20')]),
        ),
    ]
