# Generated by Django 5.1.3 on 2024-12-17 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0007_alter_scheduledmeeting_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmeeting',
            name='title',
        ),
    ]
