# Generated by Django 5.1.3 on 2024-12-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0009_alter_scheduledmeeting_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduledmeeting',
            unique_together={('day_of_week', 'slot', 'place'), ('day_of_week', 'slot', 'school_subject'), ('day_of_week', 'slot', 'teacher')},
        ),
    ]
