# Generated by Django 5.1.3 on 2025-01-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0011_remove_scheduledmeeting_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentconsent',
            name='is_consent',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('U', 'Unknown')], default='U', max_length=2),
        ),
    ]
