# Generated by Django 5.1.3 on 2025-01-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0012_alter_parentconsent_is_consent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentconsent',
            name='url',
        ),
        migrations.AddField(
            model_name='parentconsent',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='consents/'),
        ),
    ]
