# Generated by Django 5.1.3 on 2025-01-01 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0013_remove_parentconsent_url_parentconsent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentconsent',
            name='consent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_consents', to='usos_api.consenttemplate'),
        ),
    ]
