# Generated by Django 5.1.3 on 2025-01-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0014_alter_parentconsent_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentconsent',
            name='is_consent',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=2),
        ),
    ]
