# Generated by Django 5.1.3 on 2025-01-02 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0015_alter_parentconsent_is_consent'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'grade_column')},
        ),
        migrations.AlterUniqueTogether(
            name='parentconsent',
            unique_together={('parent_user', 'child_user', 'consent')},
        ),
        migrations.AlterUniqueTogether(
            name='schoolsubject',
            unique_together={('student_group', 'subject_name')},
        ),
        migrations.AlterUniqueTogether(
            name='studentgroup',
            unique_together={('section', 'level', 'name')},
        ),
    ]
