# Generated by Django 5.1.3 on 2025-01-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0016_alter_grade_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentconsent',
            name='is_consent',
            field=models.BooleanField(),
        ),
    ]
