# Generated by Django 5.1.3 on 2025-01-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usos_api', '0017_alter_parentconsent_is_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher')], max_length=10),
        ),
    ]
